#!/bin/sh
#
# description: Starts and stops the base of moServices: lighttp daemon
#
etc=/usr/local/etc
mos=$etc/mos

case "$1" in
  start | stop | status)
	;;

  enable)
	# add to rcS
	rcs=$etc/autorun.sh
	[ -f $etc/rcS ] && rcs=$etc/rcS
	grep -q 'etc/rc\.' $rcs || {
		grep -q '^/usr/local/etc/mos/services' $rcs || echo "$etc/mos/services start" >> $rcs
	}

	# add path to profile
	grep -q '# mos3 section' $etc/profile || sed -i '
/#export PATH /i\
# mos3 section\
pathmunge /usr/local/etc/mos/bin\
#\

' $etc/profile
	;;

  disable)
	# remove from profile
	sed -i '/# mos3 section/{N;N;N;d}' $etc/profile

	#remove from rcS
	rcs=$etc/autorun.sh
	[ -f $etc/rcS ] && rcs=$etc/rcS
	grep -q 'etc/rc\.' $rcs || sed -i '/etc\/mos/\services/d' $rcs
	;;

  *)
	echo "Usage: $0 {start|stop|enable|disable|status}"
	;;
esac

exit $?
