#!/bin/sh
# http://127.0.0.1/cgi-bin/aszcc?url,mime-type
# http://127.0.0.1/cgi-bin/rtmp?rtmp://streaming.cctvpic.com/vod/,mp4:v/2010/09/20/8e19b367ee8b4ade6597d5a65732f0f2_h264418000nero_aac32.mp4

URL=`echo "$QUERY_STRING" | sed 's/,.*//g'`
MP4=`echo "$QUERY_STRING" | sed 's/.*,//g'`
cat <<EOF
Content-type: video/mp4


EOF

exec /tmp_orig/www/cgi-bin/rtmpdump -r $QUERY_STRING
