#!/bin/sh
#
# Check for install libraries:
# returns 2 - embedded
# returns 1 - not installable
# returns 0 - installable
#
etc=/usr/local/etc
mos=$etc/mos

$mos/bin/ldconfig -C $etc/ld.so.cache 2>/dev/null

check=$1
[ -z $2 ] && check="$check.so"

$mos/bin/ldconfig -p | grep -q $check && exit 2
exit 0
