#!/bin/sh
#
# Check for install:
# returns 2 - embedded
# returns 1 - not installable
# returns 0 - installable
#
[ ! -f /usr/local/bin/RootApp ] && exit 1
br=$( echo $( ls -l /usr/local/bin/RootApp ) | cut -d" " -f 5 )
[ $br -eq 278836 ] && exit 2
exit 0
