#!/bin/sh

scan_pci_bus() {
	echo 1 > /sys/bus/pci/rescan
}

cleanup_pci_bus() {
	for i in $(find /sys/bus/pci/slots/ -name "power"); do
		echo 0 > $i
	done
}

remove_pci_modules() {

	for i in $(lsmod | awk '{print $1}'); do
#		echo "$(grep -c $i /lib/modules/2.6.12.6-VENUS/modules.pcimap)"
		if [ $(grep -c $i /lib/modules/2.6.12.6-VENUS/modules.pcimap) != "0" ]; then
        		echo "$i is PCI module"
			rmmod $i
		fi
	done
}

case "$1" in
	start)  echo "start pci_bus"
		scan_pci_bus
		;;
	
	stop)	echo "clean up pci bus"
		cleanup_pci_bus
		;;
		
        remove_modules) echo "clean up pci modules"
	        remove_pci_modules
                ;;
  		
	rescan)	echo "rescan pci bus"
		cleanup_pci_bus
		sleep 1
		scan_pci_bus
		;;
		
	*)	echo "usage : pci <start | stop | rescan | remove_modules | help>";;
esac

exit 0
