#!/bin/bash

ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_bookmark.fsp  usr/local/bin/guide_menu/image/Guide_bookmark.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_bookmark.png  usr/local/bin/guide_menu/image/Guide_bookmark.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_bookmark_unfocus.fsp  usr/local/bin/guide_menu/image/Guide_bookmark_unfocus.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_bookmark_unfocus.png  usr/local/bin/guide_menu/image/Guide_bookmark_unfocus.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_browser.fsp   usr/local/bin/guide_menu/image/Guide_browser.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_browser.png   usr/local/bin/guide_menu/image/Guide_browser.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_browser_unfocus.fsp   usr/local/bin/guide_menu/image/Guide_browser_unfocus.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_browser_unfocus.png   usr/local/bin/guide_menu/image/Guide_browser_unfocus.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_FileManager.fsp   usr/local/bin/guide_menu/image/Guide_FileManager.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_FileManager.png   usr/local/bin/guide_menu/image/Guide_FileManager.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_FileManager_unfocus.fsp   usr/local/bin/guide_menu/image/Guide_FileManager_unfocus.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_FileManager_unfocus.png   usr/local/bin/guide_menu/image/Guide_FileManager_unfocus.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Internet.fsp  usr/local/bin/guide_menu/image/Guide_Internet.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Internet.png  usr/local/bin/guide_menu/image/Guide_Internet.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Internet_unfocus.fsp  usr/local/bin/guide_menu/image/Guide_Internet_unfocus.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Internet_unfocus.png  usr/local/bin/guide_menu/image/Guide_Internet_unfocus.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/GuideMenu_BG_half.fsp   usr/local/bin/guide_menu/image/GuideMenu_BG_half.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/GuideMenu_BG_half.png   usr/local/bin/guide_menu/image/GuideMenu_BG_half.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Movie.fsp usr/local/bin/guide_menu/image/Guide_Movie.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Movie.png usr/local/bin/guide_menu/image/Guide_Movie.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Movie_unfocus.fsp usr/local/bin/guide_menu/image/Guide_Movie_unfocus.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Movie_unfocus.png usr/local/bin/guide_menu/image/Guide_Movie_unfocus.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Music.fsp usr/local/bin/guide_menu/image/Guide_Music.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Music.png usr/local/bin/guide_menu/image/Guide_Music.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Music_unfocus.fsp usr/local/bin/guide_menu/image/Guide_Music_unfocus.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Music_unfocus.png usr/local/bin/guide_menu/image/Guide_Music_unfocus.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Photo.fsp usr/local/bin/guide_menu/image/Guide_Photo.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Photo.png usr/local/bin/guide_menu/image/Guide_Photo.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Photo_unfocus.fsp usr/local/bin/guide_menu/image/Guide_Photo_unfocus.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Photo_unfocus.png usr/local/bin/guide_menu/image/Guide_Photo_unfocus.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Setup.fsp usr/local/bin/guide_menu/image/Guide_Setup.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Setup.png usr/local/bin/guide_menu/image/Guide_Setup.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Setup_unfocus.fsp usr/local/bin/guide_menu/image/Guide_Setup_unfocus.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Setup_unfocus.png usr/local/bin/guide_menu/image/Guide_Setup_unfocus.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Soft.fsp  usr/local/bin/guide_menu/image/Guide_Soft.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Soft.png  usr/local/bin/guide_menu/image/Guide_Soft.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Soft_unfocus.fsp  usr/local/bin/guide_menu/image/Guide_Soft_unfocus.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/guide_menu/image/Guide_Soft_unfocus.png  usr/local/bin/guide_menu/image/Guide_Soft_unfocus.png

ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/AUDIO_FOCUS.fsp usr/local/bin/home_menu/image/AUDIO_FOCUS.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/AUDIO_FOCUS.png usr/local/bin/home_menu/image/AUDIO_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/AUDIO_UNFOCUS.fsp   usr/local/bin/home_menu/image/AUDIO_UNFOCUS.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/AUDIO_UNFOCUS.png   usr/local/bin/home_menu/image/AUDIO_UNFOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/HDD_FOCUS.fsp   usr/local/bin/home_menu/image/HDD_FOCUS.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/HDD_FOCUS.png   usr/local/bin/home_menu/image/HDD_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/HDD_UNFOCUS.fsp usr/local/bin/home_menu/image/HDD_UNFOCUS.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/HDD_UNFOCUS.png usr/local/bin/home_menu/image/HDD_UNFOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/HDMI_FOCUS.fsp  usr/local/bin/home_menu/image/HDMI_FOCUS.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/HDMI_FOCUS.png  usr/local/bin/home_menu/image/HDMI_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/HDMI_UNFOCUS.fsp    usr/local/bin/home_menu/image/HDMI_UNFOCUS.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/HDMI_UNFOCUS.png    usr/local/bin/home_menu/image/HDMI_UNFOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_bookmark.fsp   usr/local/bin/home_menu/image/Home_bookmark.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_bookmark.png   usr/local/bin/home_menu/image/Home_bookmark.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_bookmark_unfocus.fsp   usr/local/bin/home_menu/image/Home_bookmark_unfocus.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_browser.fsp    usr/local/bin/home_menu/image/Home_browser.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_browser.png    usr/local/bin/home_menu/image/Home_browser.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_browser_unfocus.fsp    usr/local/bin/home_menu/image/Home_browser_unfocus.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_browser_unfocus.png    usr/local/bin/home_menu/image/Home_browser_unfocus.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_FileManager.fsp    usr/local/bin/home_menu/image/Home_FileManager.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_FileManager.png    usr/local/bin/home_menu/image/Home_FileManager.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_FileManager_unfocus.fsp    usr/local/bin/home_menu/image/Home_FileManager_unfocus.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_FileManager_unfocus.png    usr/local/bin/home_menu/image/Home_FileManager_unfocus.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Hint_Green.fsp usr/local/bin/home_menu/image/Home_Hint_Green.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Internet.fsp   usr/local/bin/home_menu/image/Home_Internet.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Internet.png   usr/local/bin/home_menu/image/Home_Internet.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Internet_unfocus.fsp   usr/local/bin/home_menu/image/Home_Internet_unfocus.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Internet_unfocus.png   usr/local/bin/home_menu/image/Home_Internet_unfocus.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/HomeMenu_BG_a.png   usr/local/bin/home_menu/image/HomeMenu_BG_a.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/HomeMenu_BG_b.png   usr/local/bin/home_menu/image/HomeMenu_BG_b.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/HomeMenu_BG_c.png   usr/local/bin/home_menu/image/HomeMenu_BG_c.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/HomeMenu_BG_d.png   usr/local/bin/home_menu/image/HomeMenu_BG_d.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/HomeMenu_BG.fsp usr/local/bin/home_menu/image/HomeMenu_BG.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Movie.fsp  usr/local/bin/home_menu/image/Home_Movie.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Movie.png  usr/local/bin/home_menu/image/Home_Movie.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Movie_unfocus.fsp  usr/local/bin/home_menu/image/Home_Movie_unfocus.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Movie_unfocus.png  usr/local/bin/home_menu/image/Home_Movie_unfocus.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Music.fsp  usr/local/bin/home_menu/image/Home_Music.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Music.png  usr/local/bin/home_menu/image/Home_Music.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Music_unfocus.fsp  usr/local/bin/home_menu/image/Home_Music_unfocus.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Music_unfocus.png  usr/local/bin/home_menu/image/Home_Music_unfocus.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Photo.fsp  usr/local/bin/home_menu/image/Home_Photo.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Photo.png  usr/local/bin/home_menu/image/Home_Photo.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Photo_unfocus.fsp  usr/local/bin/home_menu/image/Home_Photo_unfocus.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Photo_unfocus.png  usr/local/bin/home_menu/image/Home_Photo_unfocus.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Setup.fsp  usr/local/bin/home_menu/image/Home_Setup.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Setup.png  usr/local/bin/home_menu/image/Home_Setup.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Setup_unfocus.fsp  usr/local/bin/home_menu/image/Home_Setup_unfocus.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Setup_unfocus.png  usr/local/bin/home_menu/image/Home_Setup_unfocus.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Soft.fsp   usr/local/bin/home_menu/image/Home_Soft.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Soft.png   usr/local/bin/home_menu/image/Home_Soft.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Soft_unfocus.fsp   usr/local/bin/home_menu/image/Home_Soft_unfocus.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_Soft_unfocus.png   usr/local/bin/home_menu/image/Home_Soft_unfocus.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_WEB.fsp    usr/local/bin/home_menu/image/Home_WEB.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_WEB.png    usr/local/bin/home_menu/image/Home_WEB.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_WEB_unfocus.fsp    usr/local/bin/home_menu/image/Home_WEB_unfocus.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/Home_WEB_unfocus.png    usr/local/bin/home_menu/image/Home_WEB_unfocus.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/NET_FOCUS.fsp   usr/local/bin/home_menu/image/NET_FOCUS.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/NET_FOCUS.png   usr/local/bin/home_menu/image/NET_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/NET_UNFOCUS.fsp usr/local/bin/home_menu/image/NET_UNFOCUS.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/NET_UNFOCUS.png usr/local/bin/home_menu/image/NET_UNFOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/SD_FOCUS.fsp    usr/local/bin/home_menu/image/SD_FOCUS.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/SD_FOCUS.png    usr/local/bin/home_menu/image/SD_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/SD_UNFOCUS.fsp  usr/local/bin/home_menu/image/SD_UNFOCUS.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/SD_UNFOCUS.png  usr/local/bin/home_menu/image/SD_UNFOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/USB_FOCUS.fsp   usr/local/bin/home_menu/image/USB_FOCUS.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/USB_FOCUS.png   usr/local/bin/home_menu/image/USB_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/USB_UNFOCUS.fsp usr/local/bin/home_menu/image/USB_UNFOCUS.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/USB_UNFOCUS.png usr/local/bin/home_menu/image/USB_UNFOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/WIFI_FOCUS.fsp  usr/local/bin/home_menu/image/WIFI_FOCUS.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/WIFI_FOCUS.png  usr/local/bin/home_menu/image/WIFI_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/WIFI_UNFOCUS.fsp    usr/local/bin/home_menu/image/WIFI_UNFOCUS.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/WIFI_UNFOCUS.png    usr/local/bin/home_menu/image/WIFI_UNFOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/WIRE_FOCUS.fsp  usr/local/bin/home_menu/image/WIRE_FOCUS.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/WIRE_FOCUS.png  usr/local/bin/home_menu/image/WIRE_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/WIRE_UNFOCUS.fsp    usr/local/bin/home_menu/image/WIRE_UNFOCUS.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/home_menu/image/WIRE_UNFOCUS.png    usr/local/bin/home_menu/image/WIRE_UNFOCUS.png

ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMAGE_BW_EDIT_SRC_FOCUS_BAR.fsp usr/local/bin/image/IMAGE_BW_EDIT_SRC_FOCUS_BAR.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMAGE_BW_EDIT_SRC_FOCUS_BAR.png usr/local/bin/image/IMAGE_BW_EDIT_SRC_FOCUS_BAR.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMAGE_BW_EDIT_SRC_TEXT_FOCUS_BAR.fsp    usr/local/bin/image/IMAGE_BW_EDIT_SRC_TEXT_FOCUS_BAR.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMAGE_BW_EDIT_SRC_TEXT_FOCUS_BAR.png    usr/local/bin/image/IMAGE_BW_EDIT_SRC_TEXT_FOCUS_BAR.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMAGE_BW_LIST_3_TEXT_FOCUS_BAR.fsp  usr/local/bin/image/IMAGE_BW_LIST_3_TEXT_FOCUS_BAR.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMAGE_BW_LIST_3_TEXT_FOCUS_BAR.png  usr/local/bin/image/IMAGE_BW_LIST_3_TEXT_FOCUS_BAR.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMAGE_BW_LIST_FOCUS_BAR.fsp usr/local/bin/image/IMAGE_BW_LIST_FOCUS_BAR.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMAGE_BW_LIST_FOCUS_BAR.png usr/local/bin/image/IMAGE_BW_LIST_FOCUS_BAR.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMAGE_BW_LIST_TEXT_FOCUS_BAR.fsp    usr/local/bin/image/IMAGE_BW_LIST_TEXT_FOCUS_BAR.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMAGE_BW_LIST_TEXT_FOCUS_BAR.png    usr/local/bin/image/IMAGE_BW_LIST_TEXT_FOCUS_BAR.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMAGE_BW_LOGO_LOADING_0.png usr/local/bin/image/IMAGE_BW_LOGO_LOADING_0.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMAGE_BW_LOGO_LOADING_1.png usr/local/bin/image/IMAGE_BW_LOGO_LOADING_1.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMAGE_BW_LOGO_LOADING_2.png usr/local/bin/image/IMAGE_BW_LOGO_LOADING_2.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMAGE_BW_LOGO_LOADING_3.png usr/local/bin/image/IMAGE_BW_LOGO_LOADING_3.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMAGE_BW_LOGO_LOADING_4.png usr/local/bin/image/IMAGE_BW_LOGO_LOADING_4.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMAGE_BW_LOGO_LOADING_5.png usr/local/bin/image/IMAGE_BW_LOGO_LOADING_5.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMAGE_BW_LOGO_LOADING_6.png usr/local/bin/image/IMAGE_BW_LOGO_LOADING_6.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMAGE_BW_LOGO_LOADING_7.png usr/local/bin/image/IMAGE_BW_LOGO_LOADING_7.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMAGE_BW_LOGO_LOADING_8.png usr/local/bin/image/IMAGE_BW_LOGO_LOADING_8.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMAGE_NEWRSS_MENU_BTHALFFOC.fsp usr/local/bin/image/IMAGE_NEWRSS_MENU_BTHALFFOC.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMAGE_NEWRSS_MENU_BTHALFFOC.png usr/local/bin/image/IMAGE_NEWRSS_MENU_BTHALFFOC.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMS_bg.fsp  usr/local/bin/image/IMS_bg.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/IMS_bg.png  usr/local/bin/image/IMS_bg.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/list_select_bar_00.png  usr/local/bin/image/list_select_bar_00.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/loading_focus_bg.fsp    usr/local/bin/image/loading_focus_bg.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/loading_focus_bg.png    usr/local/bin/image/loading_focus_bg.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/podcast_bg_16bit.fsp    usr/local/bin/image/podcast_bg_16bit.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/podcast_bg_16bit.png    usr/local/bin/image/podcast_bg_16bit.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/POPUP_LOADING_00.png    usr/local/bin/image/POPUP_LOADING_00.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/POPUP_LOADING_01.png    usr/local/bin/image/POPUP_LOADING_01.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/POPUP_LOADING_02.png    usr/local/bin/image/POPUP_LOADING_02.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/POPUP_LOADING_03.png    usr/local/bin/image/POPUP_LOADING_03.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/POPUP_LOADING_04.png    usr/local/bin/image/POPUP_LOADING_04.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/POPUP_LOADING_05.png    usr/local/bin/image/POPUP_LOADING_05.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/POPUP_LOADING_06.png    usr/local/bin/image/POPUP_LOADING_06.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/POPUP_LOADING_07.png    usr/local/bin/image/POPUP_LOADING_07.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/POPUP_LOADING_08.png    usr/local/bin/image/POPUP_LOADING_08.png

ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/setup/scrollbar_horizontal_fg.png usr/local/bin/image/setup/scrollbar_horizontal_fg.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/image/setup/scrollbar_vertical_fg.png   usr/local/bin/image/setup/scrollbar_vertical_fg.png

ln -s   /usr/local/etc/skin_pack/usr/local/bin/menubar/image/item_normal_bar_single.bmp  usr/local/bin/menubar/image/item_normal_bar_single.bmp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/menubar/image/popmunu_focus.png   usr/local/bin/menubar/image/popmunu_focus.png

ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_ABREPEAT_SETA.png usr/local/bin/Resource/image/IMAGE_ABREPEAT_SETA.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_ABREPEAT_SETB.png usr/local/bin/Resource/image/IMAGE_ABREPEAT_SETB.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_ANGLE.png usr/local/bin/Resource/image/IMAGE_ANGLE.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_EDIT_DST_BG.png    usr/local/bin/Resource/image/IMAGE_BW_EDIT_DST_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_EDIT_DST_FOCUS_BAR.png usr/local/bin/Resource/image/IMAGE_BW_EDIT_DST_FOCUS_BAR.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_EDIT_DST_TEXT_FOCUS_BAR.png    usr/local/bin/Resource/image/IMAGE_BW_EDIT_DST_TEXT_FOCUS_BAR.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_EDIT_FOCUS_BTN.png usr/local/bin/Resource/image/IMAGE_BW_EDIT_FOCUS_BTN.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_EDIT_SRC_BG.png    usr/local/bin/Resource/image/IMAGE_BW_EDIT_SRC_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_EDIT_SRC_FOCUS_BAR.png usr/local/bin/Resource/image/IMAGE_BW_EDIT_SRC_FOCUS_BAR.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_EDIT_SRC_TEXT_FOCUS_BAR.png    usr/local/bin/Resource/image/IMAGE_BW_EDIT_SRC_TEXT_FOCUS_BAR.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_LIST_3_TEXT_FOCUS_BAR.png  usr/local/bin/Resource/image/IMAGE_BW_LIST_3_TEXT_FOCUS_BAR.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_LIST_FOCUS_BAR.png usr/local/bin/Resource/image/IMAGE_BW_LIST_FOCUS_BAR.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_LIST_TEXT_FOCUS_BAR.png    usr/local/bin/Resource/image/IMAGE_BW_LIST_TEXT_FOCUS_BAR.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_LOGO_LOADING_0.png usr/local/bin/Resource/image/IMAGE_BW_LOGO_LOADING_0.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_LOGO_LOADING_1.png usr/local/bin/Resource/image/IMAGE_BW_LOGO_LOADING_1.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_LOGO_LOADING_2.png usr/local/bin/Resource/image/IMAGE_BW_LOGO_LOADING_2.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_LOGO_LOADING_3.png usr/local/bin/Resource/image/IMAGE_BW_LOGO_LOADING_3.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_LOGO_LOADING_4.png usr/local/bin/Resource/image/IMAGE_BW_LOGO_LOADING_4.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_LOGO_LOADING_5.png usr/local/bin/Resource/image/IMAGE_BW_LOGO_LOADING_5.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_LOGO_LOADING_6.png usr/local/bin/Resource/image/IMAGE_BW_LOGO_LOADING_6.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_LOGO_LOADING_7.png usr/local/bin/Resource/image/IMAGE_BW_LOGO_LOADING_7.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_LOGO_LOADING_8.png usr/local/bin/Resource/image/IMAGE_BW_LOGO_LOADING_8.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_PREV_AUDIO_PLAYING.png usr/local/bin/Resource/image/IMAGE_BW_PREV_AUDIO_PLAYING.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_PREV_FOCUS_BAR.png usr/local/bin/Resource/image/IMAGE_BW_PREV_FOCUS_BAR.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_PREV_TEXT_FOCUS_BAR.png    usr/local/bin/Resource/image/IMAGE_BW_PREV_TEXT_FOCUS_BAR.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_THUMB_AUDIO_ALBUM.png  usr/local/bin/Resource/image/IMAGE_BW_THUMB_AUDIO_ALBUM.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_THUMB_AUDIO_ARTIST.png usr/local/bin/Resource/image/IMAGE_BW_THUMB_AUDIO_ARTIST.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_THUMB_AUDIO_FILE.png   usr/local/bin/Resource/image/IMAGE_BW_THUMB_AUDIO_FILE.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_THUMB_AUDIO_GENRE.png  usr/local/bin/Resource/image/IMAGE_BW_THUMB_AUDIO_GENRE.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_THUMB_AUDIO_PLAYLIST.png   usr/local/bin/Resource/image/IMAGE_BW_THUMB_AUDIO_PLAYLIST.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_THUMB_AUDIO_YEAR.png   usr/local/bin/Resource/image/IMAGE_BW_THUMB_AUDIO_YEAR.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_THUMB_CARDREADER.png   usr/local/bin/Resource/image/IMAGE_BW_THUMB_CARDREADER.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_THUMB_DVD.png  usr/local/bin/Resource/image/IMAGE_BW_THUMB_DVD.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_THUMB_FOCUS_FRAME_FOLDER.png   usr/local/bin/Resource/image/IMAGE_BW_THUMB_FOCUS_FRAME_FOLDER.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_THUMB_FOCUS_FRAME.png  usr/local/bin/Resource/image/IMAGE_BW_THUMB_FOCUS_FRAME.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_THUMB_FOLDER.png   usr/local/bin/Resource/image/IMAGE_BW_THUMB_FOLDER.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_THUMB_HDD.png  usr/local/bin/Resource/image/IMAGE_BW_THUMB_HDD.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_THUMB_INVALID.png  usr/local/bin/Resource/image/IMAGE_BW_THUMB_INVALID.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_THUMB_NETWORK.png  usr/local/bin/Resource/image/IMAGE_BW_THUMB_NETWORK.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_THUMB_PHOTO_ALBUM.png  usr/local/bin/Resource/image/IMAGE_BW_THUMB_PHOTO_ALBUM.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_THUMB_UNFOCUS_FRAME_FOLDER.png usr/local/bin/Resource/image/IMAGE_BW_THUMB_UNFOCUS_FRAME_FOLDER.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_THUMB_UNFOCUS_FRAME.png    usr/local/bin/Resource/image/IMAGE_BW_THUMB_UNFOCUS_FRAME.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_THUMB_UPNP.png usr/local/bin/Resource/image/IMAGE_BW_THUMB_UPNP.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_THUMB_USB.png  usr/local/bin/Resource/image/IMAGE_BW_THUMB_USB.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_THUMB_VIDEO_FILE.png   usr/local/bin/Resource/image/IMAGE_BW_THUMB_VIDEO_FILE.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_THUMB_VIDEO_FLASH.png  usr/local/bin/Resource/image/IMAGE_BW_THUMB_VIDEO_FLASH.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_BW_UNCHECK_ICON.png   usr/local/bin/Resource/image/IMAGE_BW_UNCHECK_ICON.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_CH_LIST_SCROLLBAR_FG.png  usr/local/bin/Resource/image/IMAGE_CH_LIST_SCROLLBAR_FG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_CMSKIP.png    usr/local/bin/Resource/image/IMAGE_CMSKIP.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_COLOR_KEY_BLUE.png    usr/local/bin/Resource/image/IMAGE_COLOR_KEY_BLUE.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_COLOR_KEY_GREEN.png   usr/local/bin/Resource/image/IMAGE_COLOR_KEY_GREEN.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_COLOR_KEY_RED.png usr/local/bin/Resource/image/IMAGE_COLOR_KEY_RED.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_COLOR_KEY_YELLOW.png  usr/local/bin/Resource/image/IMAGE_COLOR_KEY_YELLOW.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_COMMON_BG.png usr/local/bin/Resource/image/IMAGE_COMMON_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_COMMON_EDIT_BG.png    usr/local/bin/Resource/image/IMAGE_COMMON_EDIT_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_COMMON_PURE_BG.png    usr/local/bin/Resource/image/IMAGE_COMMON_PURE_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_CONFIRM_WINDOW_BG.png usr/local/bin/Resource/image/IMAGE_CONFIRM_WINDOW_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_CONFIRM_WINDOW.png    usr/local/bin/Resource/image/IMAGE_CONFIRM_WINDOW.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DIALOG_MENU_BG.png    usr/local/bin/Resource/image/IMAGE_DIALOG_MENU_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DIALOG_MENU_BTN_FOCUS.png usr/local/bin/Resource/image/IMAGE_DIALOG_MENU_BTN_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DIALOG_MENU_NEW_BTN_FOCUS.png usr/local/bin/Resource/image/IMAGE_DIALOG_MENU_NEW_BTN_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISC_BUSY.png usr/local/bin/Resource/image/IMAGE_DISC_BUSY.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISC_CD.png   usr/local/bin/Resource/image/IMAGE_DISC_CD.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISC_DVD_MINUSR.png   usr/local/bin/Resource/image/IMAGE_DISC_DVD_MINUSR.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISC_DVD_MINUSRW.png  usr/local/bin/Resource/image/IMAGE_DISC_DVD_MINUSRW.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISC_DVD_PLUSR.png    usr/local/bin/Resource/image/IMAGE_DISC_DVD_PLUSR.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISC_DVD_PLUSRW.png   usr/local/bin/Resource/image/IMAGE_DISC_DVD_PLUSRW.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISC_DVD.png  usr/local/bin/Resource/image/IMAGE_DISC_DVD.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISC_SVCD.png usr/local/bin/Resource/image/IMAGE_DISC_SVCD.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISC_VCD.png  usr/local/bin/Resource/image/IMAGE_DISC_VCD.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISPLAY_CD.png    usr/local/bin/Resource/image/IMAGE_DISPLAY_CD.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISPLAY_DISC.png  usr/local/bin/Resource/image/IMAGE_DISPLAY_DISC.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISPLAY_DVD_MINUSR.png    usr/local/bin/Resource/image/IMAGE_DISPLAY_DVD_MINUSR.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISPLAY_DVD_MINUSRW.png   usr/local/bin/Resource/image/IMAGE_DISPLAY_DVD_MINUSRW.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISPLAY_DVD_PLUSR.png usr/local/bin/Resource/image/IMAGE_DISPLAY_DVD_PLUSR.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISPLAY_DVD_PLUSRW.png    usr/local/bin/Resource/image/IMAGE_DISPLAY_DVD_PLUSRW.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISPLAY_DVD.png   usr/local/bin/Resource/image/IMAGE_DISPLAY_DVD.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISPLAY_HDD.png   usr/local/bin/Resource/image/IMAGE_DISPLAY_HDD.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISPLAY_NET.png   usr/local/bin/Resource/image/IMAGE_DISPLAY_NET.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISPLAY.png   usr/local/bin/Resource/image/IMAGE_DISPLAY.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISPLAY_SVCD.png  usr/local/bin/Resource/image/IMAGE_DISPLAY_SVCD.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISPLAY_USB.png   usr/local/bin/Resource/image/IMAGE_DISPLAY_USB.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISPLAY_VCD.png   usr/local/bin/Resource/image/IMAGE_DISPLAY_VCD.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISPLAY_WIRELESS_CONNECTED.png    usr/local/bin/Resource/image/IMAGE_DISPLAY_WIRELESS_CONNECTED.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_DISPLAY_WIRELESS_DISCONNECTED.png usr/local/bin/Resource/image/IMAGE_DISPLAY_WIRELESS_DISCONNECTED.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_EDIT_SCROLL_BAR_BG.png    usr/local/bin/Resource/image/IMAGE_EDIT_SCROLL_BAR_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_EJECT.png usr/local/bin/Resource/image/IMAGE_EJECT.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_EPG_DATE_SEL_FOCUS.png    usr/local/bin/Resource/image/IMAGE_EPG_DATE_SEL_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_EPGs_CHANNEL_SEL_FOCUS.png    usr/local/bin/Resource/image/IMAGE_EPGs_CHANNEL_SEL_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_EPGs_DATE.png usr/local/bin/Resource/image/IMAGE_EPGs_DATE.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_EPGs_PROGRAM_DETAIL_BG.png    usr/local/bin/Resource/image/IMAGE_EPGs_PROGRAM_DETAIL_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_EPGs_PROGRAM_SEL_FOCUS.png    usr/local/bin/Resource/image/IMAGE_EPGs_PROGRAM_SEL_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_FAIL.png  usr/local/bin/Resource/image/IMAGE_FAIL.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_FFWD.png  usr/local/bin/Resource/image/IMAGE_FFWD.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_FILE_COPY_CANCEL_BTN.png  usr/local/bin/Resource/image/IMAGE_FILE_COPY_CANCEL_BTN.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_FOCUS_MENU_BAR.png    usr/local/bin/Resource/image/IMAGE_FOCUS_MENU_BAR.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_FORBIDDEN.png usr/local/bin/Resource/image/IMAGE_FORBIDDEN.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_HDD_FORBIDDEN.png usr/local/bin/Resource/image/IMAGE_HDD_FORBIDDEN.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_HDD_FORMAT_WARNING1.png   usr/local/bin/Resource/image/IMAGE_HDD_FORMAT_WARNING1.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_HDD.png   usr/local/bin/Resource/image/IMAGE_HDD.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_HINT_DELETE.png   usr/local/bin/Resource/image/IMAGE_HINT_DELETE.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_HINT_MOVE_CURSOR.png  usr/local/bin/Resource/image/IMAGE_HINT_MOVE_CURSOR.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_HINT_RETURN_CASE.png  usr/local/bin/Resource/image/IMAGE_HINT_RETURN_CASE.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_HINT_RETURN_INPUT_METHO.png   usr/local/bin/Resource/image/IMAGE_HINT_RETURN_INPUT_METHO.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_HINT_RETURN.png   usr/local/bin/Resource/image/IMAGE_HINT_RETURN.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_HINT_RETURN_SYMBOL.png    usr/local/bin/Resource/image/IMAGE_HINT_RETURN_SYMBOL.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_INFO_BAR_BG.png   usr/local/bin/Resource/image/IMAGE_INFO_BAR_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_INFO_BAR_BTN1_BG.png  usr/local/bin/Resource/image/IMAGE_INFO_BAR_BTN1_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_INFO_BAR_BTN2_BG.png  usr/local/bin/Resource/image/IMAGE_INFO_BAR_BTN2_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_INFO_BAR_PROGRESS_BG.png  usr/local/bin/Resource/image/IMAGE_INFO_BAR_PROGRESS_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_INFO_BAR_SCROLLBAR_BG.png usr/local/bin/Resource/image/IMAGE_INFO_BAR_SCROLLBAR_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_INFO_BAR_STORAGE_BTN.png  usr/local/bin/Resource/image/IMAGE_INFO_BAR_STORAGE_BTN.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_INFO_DESCRIPTION_BG.png   usr/local/bin/Resource/image/IMAGE_INFO_DESCRIPTION_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_INS_REPLAY.png    usr/local/bin/Resource/image/IMAGE_INS_REPLAY.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_INSTANT_REPEAT.png    usr/local/bin/Resource/image/IMAGE_INSTANT_REPEAT.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_L3FOCUS.png   usr/local/bin/Resource/image/IMAGE_L3FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_LOADING_1.png usr/local/bin/Resource/image/IMAGE_LOADING_1.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_LOADING_2.png usr/local/bin/Resource/image/IMAGE_LOADING_2.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_LOADING_3.png usr/local/bin/Resource/image/IMAGE_LOADING_3.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_LOADING_4.png usr/local/bin/Resource/image/IMAGE_LOADING_4.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_LOADING.png   usr/local/bin/Resource/image/IMAGE_LOADING.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_MEDIA_AUDIO.png   usr/local/bin/Resource/image/IMAGE_MEDIA_AUDIO.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_MINIB_BG.png  usr/local/bin/Resource/image/IMAGE_MINIB_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_MINIB_LIST_FOCUS_BG.png   usr/local/bin/Resource/image/IMAGE_MINIB_LIST_FOCUS_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_MINIB_LIST_TEXT_FOCUS_BG.png  usr/local/bin/Resource/image/IMAGE_MINIB_LIST_TEXT_FOCUS_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_MOVIE_INFO_BG.png usr/local/bin/Resource/image/IMAGE_MOVIE_INFO_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_MOVIE_INFO_PROGRESS_BAR_BG.png    usr/local/bin/Resource/image/IMAGE_MOVIE_INFO_PROGRESS_BAR_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_MOVIE_INFO_RPT_ALL.png    usr/local/bin/Resource/image/IMAGE_MOVIE_INFO_RPT_ALL.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_MOVIE_INFO_RPT_CHAPTER.png    usr/local/bin/Resource/image/IMAGE_MOVIE_INFO_RPT_CHAPTER.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_MOVIE_INFO_RPT_OFF.png    usr/local/bin/Resource/image/IMAGE_MOVIE_INFO_RPT_OFF.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_MOVIE_INFO_RPT_TITLE.png  usr/local/bin/Resource/image/IMAGE_MOVIE_INFO_RPT_TITLE.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_MUTE.png  usr/local/bin/Resource/image/IMAGE_MUTE.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_NEWRSS_MENU_BTFOC.png usr/local/bin/Resource/image/IMAGE_NEWRSS_MENU_BTFOC.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_NEWRSS_MENU_BTHALFFOC.png usr/local/bin/Resource/image/IMAGE_NEWRSS_MENU_BTHALFFOC.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_NEWRSS_MENU_BTUFOC.png    usr/local/bin/Resource/image/IMAGE_NEWRSS_MENU_BTUFOC.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_NEXT.png  usr/local/bin/Resource/image/IMAGE_NEXT.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_OPTION_BUTTON_FOCUS.png   usr/local/bin/Resource/image/IMAGE_OPTION_BUTTON_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_OPTION_INDICATOR_DOWN.png usr/local/bin/Resource/image/IMAGE_OPTION_INDICATOR_DOWN.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_OPTION_INDICATOR_UP.png   usr/local/bin/Resource/image/IMAGE_OPTION_INDICATOR_UP.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_PAUSE.png usr/local/bin/Resource/image/IMAGE_PAUSE.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_PLAYBACK_SEARCH_FOCUSED.png   usr/local/bin/Resource/image/IMAGE_PLAYBACK_SEARCH_FOCUSED.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_PLAY.png  usr/local/bin/Resource/image/IMAGE_PLAY.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_PREV.png  usr/local/bin/Resource/image/IMAGE_PREV.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_PROGRESS_BAR_BG.png   usr/local/bin/Resource/image/IMAGE_PROGRESS_BAR_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_REC_PAUSE.png usr/local/bin/Resource/image/IMAGE_REC_PAUSE.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_REC.png   usr/local/bin/Resource/image/IMAGE_REC.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_REC_STOP.png  usr/local/bin/Resource/image/IMAGE_REC_STOP.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_REPEAT_ALL.png    usr/local/bin/Resource/image/IMAGE_REPEAT_ALL.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_REPEAT_OFF.png    usr/local/bin/Resource/image/IMAGE_REPEAT_OFF.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_REPEAT_SHUFFLE.png    usr/local/bin/Resource/image/IMAGE_REPEAT_SHUFFLE.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_REPEAT_TRACK.png  usr/local/bin/Resource/image/IMAGE_REPEAT_TRACK.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_REW.png   usr/local/bin/Resource/image/IMAGE_REW.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_RW_STEP.png   usr/local/bin/Resource/image/IMAGE_RW_STEP.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_SAMBA_BLANK_FOCUS.png usr/local/bin/Resource/image/IMAGE_SAMBA_BLANK_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_SAMBA_BUTTON_FOCUS.png    usr/local/bin/Resource/image/IMAGE_SAMBA_BUTTON_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_SAMBA_BUTTON_LARGE_FOCUS.png  usr/local/bin/Resource/image/IMAGE_SAMBA_BUTTON_LARGE_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_SAMBA_IP_FOCUS.png    usr/local/bin/Resource/image/IMAGE_SAMBA_IP_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_SAMBA_IP_INPUT_DOT.png    usr/local/bin/Resource/image/IMAGE_SAMBA_IP_INPUT_DOT.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_SAMBA_LARGE_BLANK_FOCUS.png   usr/local/bin/Resource/image/IMAGE_SAMBA_LARGE_BLANK_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_SCREENSAVER_LOGO.png  usr/local/bin/Resource/image/IMAGE_SCREENSAVER_LOGO.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_SLOW.png  usr/local/bin/Resource/image/IMAGE_SLOW.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_SOURCE_MSG.png    usr/local/bin/Resource/image/IMAGE_SOURCE_MSG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_STEP.png  usr/local/bin/Resource/image/IMAGE_STEP.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_STOP.png  usr/local/bin/Resource/image/IMAGE_STOP.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_SUBTITLEMENU_FOCUS.png    usr/local/bin/Resource/image/IMAGE_SUBTITLEMENU_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_SUBTITLEMENU_FRAME_A_FOCUS.png    usr/local/bin/Resource/image/IMAGE_SUBTITLEMENU_FRAME_A_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_SUBTITLEMENU_FRAME_B_FOCUS.png    usr/local/bin/Resource/image/IMAGE_SUBTITLEMENU_FRAME_B_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_TIMER_ARROW_DOWN_FOCUS.png    usr/local/bin/Resource/image/IMAGE_TIMER_ARROW_DOWN_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_TIMER_ARROW_DOWN_UNFOCUS.png  usr/local/bin/Resource/image/IMAGE_TIMER_ARROW_DOWN_UNFOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_TIMER_ARROW_UP_FOCUS.png  usr/local/bin/Resource/image/IMAGE_TIMER_ARROW_UP_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_TIMER_ARROW_UP_UNFOCUS.png    usr/local/bin/Resource/image/IMAGE_TIMER_ARROW_UP_UNFOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_TIMER_BG.png  usr/local/bin/Resource/image/IMAGE_TIMER_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_TIMER_DATE_UNFOCUS.png    usr/local/bin/Resource/image/IMAGE_TIMER_DATE_UNFOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_TIMER_EDIT_BG.png usr/local/bin/Resource/image/IMAGE_TIMER_EDIT_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_TIMER_OK.png  usr/local/bin/Resource/image/IMAGE_TIMER_OK.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_TIMER_REPEAT_CYCLE.png    usr/local/bin/Resource/image/IMAGE_TIMER_REPEAT_CYCLE.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_TIMER_REPEAT_FOCUS.png    usr/local/bin/Resource/image/IMAGE_TIMER_REPEAT_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_TIMER_SCHEDULE_FOCUS.png  usr/local/bin/Resource/image/IMAGE_TIMER_SCHEDULE_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_TIMER_SRC_FOCUS.png   usr/local/bin/Resource/image/IMAGE_TIMER_SRC_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_TIMER_START_FOCUS.png usr/local/bin/Resource/image/IMAGE_TIMER_START_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_TIMER_TIME_FOCUS.png  usr/local/bin/Resource/image/IMAGE_TIMER_TIME_FOCUS.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_TIMESHIFT_BAR_BG.png  usr/local/bin/Resource/image/IMAGE_TIMESHIFT_BAR_BG.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_VENDOR_SCROLL_BAR.png usr/local/bin/Resource/image/IMAGE_VENDOR_SCROLL_BAR.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_VOLUME_HIGHLIGHT.png  usr/local/bin/Resource/image/IMAGE_VOLUME_HIGHLIGHT.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/Resource/image/IMAGE_ZOOM.png  usr/local/bin/Resource/image/IMAGE_ZOOM.png

ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/664_focus.fsp   usr/local/bin/setup_menu/image/664_focus.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/664_focus.png   usr/local/bin/setup_menu/image/664_focus.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/progressbar_horizontal_fg.png   usr/local/bin/setup_menu/image/progressbar_horizontal_fg.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/progressbar_vertical_fg.png usr/local/bin/setup_menu/image/progressbar_vertical_fg.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/scroll_bar_02.fsp   usr/local/bin/setup_menu/image/scroll_bar_02.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/scroll_bar_03.fsp   usr/local/bin/setup_menu/image/scroll_bar_03.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/scroll_bar_03.png   usr/local/bin/setup_menu/image/scroll_bar_03.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_input_foucs_bg.fsp    usr/local/bin/setup_menu/image/setup_input_foucs_bg.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_input_foucs_bg.png    usr/local/bin/setup_menu/image/setup_input_foucs_bg.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_input_unfoucs_bg.fsp  usr/local/bin/setup_menu/image/setup_input_unfoucs_bg.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_input_unfoucs_bg.png  usr/local/bin/setup_menu/image/setup_input_unfoucs_bg.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_ip_bg.fsp usr/local/bin/setup_menu/image/setup_ip_bg.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_ip_bg.png usr/local/bin/setup_menu/image/setup_ip_bg.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_p2_list_focus.fsp usr/local/bin/setup_menu/image/setup_p2_list_focus.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_p2_list_focus.png usr/local/bin/setup_menu/image/setup_p2_list_focus.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bar_focus.png   usr/local/bin/setup_menu/image/setup_popup_bar_focus.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bar_focus_wide.png  usr/local/bin/setup_menu/image/setup_popup_bar_focus_wide.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_edit.fsp usr/local/bin/setup_menu/image/setup_popup_bg_edit.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_edit.png usr/local/bin/setup_menu/image/setup_popup_bg_edit.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg.fsp  usr/local/bin/setup_menu/image/setup_popup_bg.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_line.fsp usr/local/bin/setup_menu/image/setup_popup_bg_line.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_line.png usr/local/bin/setup_menu/image/setup_popup_bg_line.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_normal_bottom.fsp    usr/local/bin/setup_menu/image/setup_popup_bg_normal_bottom.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_normal_bottom.png    usr/local/bin/setup_menu/image/setup_popup_bg_normal_bottom.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_normal_middle.fsp    usr/local/bin/setup_menu/image/setup_popup_bg_normal_middle.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_normal_middle.png    usr/local/bin/setup_menu/image/setup_popup_bg_normal_middle.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_normal_top.fsp   usr/local/bin/setup_menu/image/setup_popup_bg_normal_top.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_normal_top.png   usr/local/bin/setup_menu/image/setup_popup_bg_normal_top.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg.png  usr/local/bin/setup_menu/image/setup_popup_bg.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_simple.bmp   usr/local/bin/setup_menu/image/setup_popup_bg_simple.bmp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_simple_bottom.fsp    usr/local/bin/setup_menu/image/setup_popup_bg_simple_bottom.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_simple_bottom.png    usr/local/bin/setup_menu/image/setup_popup_bg_simple_bottom.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_simple.fsp   usr/local/bin/setup_menu/image/setup_popup_bg_simple.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_simple_middle.fsp    usr/local/bin/setup_menu/image/setup_popup_bg_simple_middle.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_simple_middle.png    usr/local/bin/setup_menu/image/setup_popup_bg_simple_middle.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_simple.png   usr/local/bin/setup_menu/image/setup_popup_bg_simple.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_simple_top.fsp   usr/local/bin/setup_menu/image/setup_popup_bg_simple_top.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_simple_top.png   usr/local/bin/setup_menu/image/setup_popup_bg_simple_top.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_wide_bottom.fsp  usr/local/bin/setup_menu/image/setup_popup_bg_wide_bottom.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_wide_bottom.png  usr/local/bin/setup_menu/image/setup_popup_bg_wide_bottom.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_wide_middle.fsp  usr/local/bin/setup_menu/image/setup_popup_bg_wide_middle.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_wide_middle.png  usr/local/bin/setup_menu/image/setup_popup_bg_wide_middle.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_wide_top.fsp usr/local/bin/setup_menu/image/setup_popup_bg_wide_top.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/setup_popup_bg_wide_top.png usr/local/bin/setup_menu/image/setup_popup_bg_wide_top.png
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/video_setting_frame.fsp usr/local/bin/setup_menu/image/video_setting_frame.fsp
ln -s   /usr/local/etc/skin_pack/usr/local/bin/setup_menu/image/video_setting_frame.png usr/local/bin/setup_menu/image/video_setting_frame.png
