#!/bin/sh
#
#   http://code.google.com/media-translate/
#   Copyright (C) 2010  Serge A. Timchenko
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.
#

DATAPATH=$BASEPATH/app/poiskm
cd $DATAPATH

get_opt "q"
local SEARCH=$opt

get_opt "opt"
local OPT=$opt

if [ -z "$SEARCH" ]; then 
  SEARCH=$arg_opt
  OPT='c=search&xbds=1'
fi

local CHANNELFILE="$CACHEPATH/poiskm.search.`echo -n \"$SEARCH\" | sed 's/[^a-zA-z0-9_\-]/_/g'`.cache"
local TEMPDL=$TMPFILE.dl

local TIMELIFE=3600

let tsttime=`date +%s`-$TIMELIFE

REFRESHCACHE=yes
if [ -f "$CHANNELFILE" ]; then
  if [ "`ls -s "$CHANNELFILE" | awk '{print $1}'`" != "0" ]; then
    if [ `date +%s -r "$CHANNELFILE"` -gt $tsttime ]; then
      REFRESHCACHE=
    fi
  fi
fi

local TITLE="Poiskm.ru - $SEARCH"

if [ $REFRESHCACHE ]; then
  $WGET -q -O "$TEMPDL" --header "User-Agent: $USERAGENT" "http://poiskm.ru/?q=`urlencode_s "$SEARCH"`${OPT:+&$OPT}"
  if [ -f "$TEMPDL" ]; then
    if [ "`ls -s "$TEMPDL" | awk '{print $1}'`" != "0" ]; then
      $XSLTPROC --encoding utf-8 --html --stringparam title "$TITLE" search.xslt "$TEMPDL" 2>/dev/null > $CHANNELFILE
    fi
    rm -f "$TEMPDL"
  fi
fi

cat $CHANNELFILE | printContent "application/xspf+xml" 
